### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by kyegomez** [daveshap/ACE_Framework#14]
Hey, nice project but I don't see any code, where is it? or maybe i am dumb

**Comment by DataBassGit** [comment]
It's in the works.  That said, the paper was published this morning, you are a prolific developer so feel free to write an implementation.

The ACE Framework isn't specifically an end solution, like TCP/IP is a network protocol. Instead, it's a model or reference, like the OSI model, from CompTIA. It's an idea about how to design autonomous systems that run continuously and reactively, rather than relying on a user to give them an objective.

Right now, we're defining the systems and protocols we will be using for the POC. It looks like we'll be using AMQP for interagent communication, logging to disk, and building on openai. We will probably incorporate a vector store (pinecone to keep it light weight) and maybe a knowledge graph. The team has some UI guys, too.
